services:
  - type: web
    name: sport
    runtime: node
    plan: free
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: GITHUB_TOKEN
        sync: false
      - key: GITHUB_REPO
        value: cemxbt/sport
